# Generated by Django 5.0.1 on 2024-01-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IhaData',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Stock', models.IntegerField()),
                ('YearUnitFee', models.FloatField()),
                ('Currency', models.CharField(default='₺', max_length=50)),
                ('IsForRent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserWindowIha',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PurpchaseDate', models.IntegerField(default=2024)),
                ('PurpchaseEndDate', models.IntegerField()),
                ('PurpchaseQuantity', models.IntegerField(default=0)),
                ('TotalFee', models.FloatField(default=0)),
                ('Currency', models.CharField(default='₺', editable=False, max_length=50)),
                ('IhaId', models.ForeignKey(limit_choices_to={'IsForRent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='IhaApp.ihadata')),
            ],
        ),
    ]
