# Generated by Django 5.0.1 on 2024-01-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaApp', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihadata',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userwindowiha',
            name='IhaId',
            field=models.ForeignKey(limit_choices_to={'IsDelete': False, 'IsForRent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IhaApp.ihadata'),
        ),
    ]
